ServiEnCasa_v01/Models/Tareas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiEnCasa_v01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tareas()
        {
            this.Solicitudes = new HashSet<Solicitudes>();
            this.Servis = new HashSet<Servis>();
        }
    
        public int Id_Tarea { get; set; }
        public string Desc_Tarea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servis> Servis { get; set; }
        public virtual Profesiones Profesiones { get; set; }
    }
}

ServiEnCasa_v01/Controllers/TareasController.cs
using ServiEnCasa_v01.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ServiEnCasa_v01.Controllers
{
    public class TareasController : Controller
    {
        // crear una instancia desde la base de datos.
        private ModeloContainer db = new ModeloContainer();
        //
        // GET: Tareas
        public ActionResult Index(int? ProfesionID)
        {
            if (ProfesionID == null)
            {
                ViewBag.ProfesionID = new SelectList(db.Profesiones.ToList(), "Id_Profesion", "Desc_Profesion");
                return View(db.Tareas.ToList());
            }
            else
            {

                ViewBag.ProfesionID = new SelectList(db.Profesiones.ToList(), "Id_Profesion", "Desc_Profesion");
                var resultado = db.Tareas.Where(x => x.Profesiones.Id_Profesion == ProfesionID).ToList();
                return View(resultado);
            }
        }
        
        [HttpPost]
        public ActionResult Busqueda(int ProfesionID)
        {
            var resultado = db.Tareas.Where(x => x.Profesiones.Id_Profesion == ProfesionID).ToList();
            return View(resultado);
        }

        // GET: Tareas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Tareas/Create
        public ActionResult Create()
        {
            ViewBag.ProfesionID = new SelectList(db.Profesiones.ToList(), "Id_Profesion", "Desc_Profesion");
            return View();
        }

        // POST: Tareas/Create
        [HttpPost]
        public ActionResult Create(CrearTareaViewModel vmCrearTarea)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var prof = db.Profesiones.Find(vmCrearTarea.ProfesionID);
                    var tarea = new Tareas { Desc_Tarea = vmCrearTarea.tarea, Profesiones = prof };
                    if (ValidaTarea(tarea.Desc_Tarea.ToString(), tarea.Profesiones.Id_Profesion) == false)
                    {
                        db.Tareas.Add(tarea);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                ViewBag.ProfesionID = new SelectList(db.Profesiones.ToList(), "Id_Profesion", "Desc_Profesion");
                return View();
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: Tareas/Edit/5
        public ActionResult Edit(int id)
        {

            var tarea = db.Tareas.Find(id);

            if (tarea == null)
            {
                return HttpNotFound();
            }
            var ViewModel = new EditarTareaViewModel()
            {
                profesion = tarea.Profesiones.Desc_Profesion,
                tarea = tarea.Desc_Tarea
            };

            return View(ViewModel);
        }

        // POST: Tareas/Edit/5
        [HttpPost]
        public ActionResult Edit(EditarTareaViewModel vmEditar)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var Editar = db.Tareas.Find(vmEditar.id);
                    string desc = vmEditar.tarea;
                    if (desc.ToUpper() != Editar.Desc_Tarea.ToString().ToUpper())
                    {
                        if (ValidaTarea(desc,vmEditar.id) == false)
                        {
                            Editar.Desc_Tarea = vmEditar.tarea;
                            db.Entry(Editar).State = System.Data.Entity.EntityState.Modified;
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                    }
                    return View();
                }
                // TODO: Add update logic here
            }
            catch
            {
                return View();
            }
            return View();
        }

        // GET: Tareas/Delete/5
        public ActionResult Delete(int id)
        {
            var tareas = db.Tareas.Find(id);
            if (tareas == null)
            {
                return HttpNotFound();
            }
            return View(tareas);
        }

        // POST: Tareas/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult ConfirmarEliminar(int id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var tarea = db.Tareas.Find(id);
                if (tarea == null)
                {
                    return HttpNotFound();
                }

                db.Entry(tarea).State = System.Data.Entity.EntityState.Deleted;
                db.SaveChanges();

                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public bool ValidaTarea(string t, int id)
        {
            foreach (Tareas oTarea in db.Tareas.ToList())
            {
                if (oTarea.Desc_Tarea.ToUpper() == t.ToUpper() && oTarea.Profesiones.Id_Profesion == id )
                {
                    return true;
                }
            }
            return false;
        }
    }
}

ServiEnCasa_v01/Views/Tareas/Create.cshtml
@model ServiEnCasa_v01.Models.CrearTareaViewModel
@{
    ViewBag.Title = "Alta de Tareas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alta de Tareas</h2>
@Html.AntiForgeryToken()
@using (Html.BeginForm("Create", "Tareas", FormMethod.Post))
{
    <div class="row">
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.ProfesionID, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.DropDownList("ProfesionID", (SelectList)ViewBag.ProfesionID, "Seleccionar Profesión", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ProfesionID, "", new { @class = "text-danger" })
                 </div>
        </div>
            <div class="form-group">
                @Html.LabelFor(m => m.tarea, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.tarea, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.tarea, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <br />
                    <input type="submit" value="Aceptar" class="btn btn-success" />
                    @Html.ActionLink("Cancelar", "Index", "Tareas", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    </div>
}

ServiEnCasa_v01/Views/Tareas/Delete.cshtml
@model ServiEnCasa_v01.Models.Tareas
@{
    ViewBag.Title = "Eliminar Tareas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Tareas</h2>
<hr />
<h3>¿Esta seguro de eliminar la Tarea?</h3>
<br />
<h3>@Html.DisplayFor(model => model.Desc_Tarea)</h3>
<h3>De la Profesión: @Html.DisplayFor(model => model.Profesiones.Desc_Profesion)</h3>
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        @Html.ActionLink("Cancelar", "Index", "Tareas", null, new { @class = "btn btn-default" })
    </div>
}

ServiEnCasa_v01/Views/Tareas/Edit.cshtml
@model ServiEnCasa_v01.Models.EditarTareaViewModel
@{
    ViewBag.Title = "Editar Tarea";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Tarea</h2>
@Html.AntiForgeryToken()
@using (Html.BeginForm("Edit", "Tareas", FormMethod.Post))
{
    <div class="row">
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.profesion, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.profesion, new { @class = "form-control" , @disabled = "disabled"})
                    @Html.ValidationMessageFor(m => m.profesion, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.tarea, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.tarea, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.tarea, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <br />
                    <input type="submit" value="Aceptar" class="btn btn-success" />
                    @Html.ActionLink("Cancelar", "Index", "Tareas", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    </div>
}

ServiEnCasa_v01/Views/Tareas/Index.cshtml
@model IEnumerable<ServiEnCasa_v01.Models.Tareas>

@{
    ViewBag.Title = "Tareas";
    Layout = "~/Views/Shared/_LayoutDash.cshtml";
}

<h2>Tareas</h2>
<hr />
<div class="container">
    <div class="row col-md-6 col-md-offset-2 custyle">
        <div class="form-group">
            @using (Html.BeginForm("Index", "Tareas", FormMethod.Post))
            {
                @Html.DropDownList("ProfesionID", (SelectList)ViewBag.ProfesionID, "Seleccionar Profesión", new { @class = "form-control" })
                <br />
                <input type="submit" value="Buscar" class="btn btn-primary" />
            }
             <a href="@Url.Action("Create", "Tareas")" class="btn btn-primary btn-xs pull-right"><b>+</b> Agregar Nueva Tarea </a>
        </div>
        <table id="tareas" class="table table-striped custab">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tarea</th>
                    <th>Profesión</th>
                    <th class="text-center">Acción</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Any())
                    {
                        foreach (var p in Model)
                        {
                            <tr>
                                <td class='actualizar'>@p.Id_Tarea</td>
                                <td class='actualizar'>@p.Desc_Tarea</td>
                                <td class='actualizar'>@p.Profesiones.Desc_Profesion.ToString()</td>
                                <td class="text-center">
                                    <a class='btn btn-info btn-xs' href="@Url.Action("Edit","Tareas",new { id = p.Id_Tarea})"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                                    <a href="@Url.Action("Delete","Tareas",new { id = p.Id_Tarea})" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Eliminar</a>
                                </td>
                            </tr>
                        }
                    }
            </tbody>
        </table>
    </div>
    </div>