ServiEnCasa_v01/Models/Zonas.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiEnCasa_v01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zonas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zonas()
        {
            this.Solicitudes = new HashSet<Solicitudes>();
        }
    
        public int Id_Zona { get; set; }
        public string Zona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
    }
}

ServiEnCasa_v01/Controllers/ZonasController.cs
using ServiEnCasa_v01.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ServiEnCasa_v01.Controllers
{
    public class ZonasController : Controller
    {
        //Instanciar la Base de Datos
        private ModeloContainer db = new ModeloContainer();
        //
        // GET: Zonas
        public ActionResult Index()
        {
            return View(db.Zonas.ToList());
        }

        // GET: Zonas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Zonas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Zonas/Create
        [HttpPost]
        public ActionResult Create(ZonasViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var zona = new Zonas { Zona = viewModel.zona };
                    if (ValidaZona(zona.Zona.ToString()) == false)
                    {
                        db.Zonas.Add(zona);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                return View();
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        // GET: Zonas/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var zona = db.Zonas.Find(id);
            if (zona == null)
            {
                return HttpNotFound();
            }
            var ViewModel = new ZonasViewModel()
            {
                zona = zona.Zona
            };

            return View(ViewModel);
        }

        // POST: Zonas/Edit/5
        [HttpPost]
        public ActionResult Edit(ZonasViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var Editar = db.Zonas.Find(viewModel.id);
                    string zona = viewModel.zona;
                    if (zona.ToUpper() != Editar.Zona.ToString().ToUpper())
                    {
                        if (ValidaZona(zona) == false)
                        {
                            Editar.Zona = viewModel.zona;
                            db.Entry(Editar).State = System.Data.Entity.EntityState.Modified;
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                    }
                    return View();
                }
                // TODO: Add update logic here
            }
            catch
            {
                return View();
            }
            return View();
        }

        // GET: Zonas/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var zona = db.Zonas.Find(id);
            if (zona == null)
            {
                return HttpNotFound();
            }
            return View(zona);
        }

        // POST: Zonas/Delete/5
        [HttpPost, ActionName ("Delete")]
        public ActionResult ConfirmarEliminacion(int id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var zona = db.Zonas.Find(id);
                if (zona == null)
                {
                    return HttpNotFound();
                }
                if (zona.Solicitudes.Count() >= 0)
                {
                    db.Entry(zona).State = System.Data.Entity.EntityState.Deleted;
                    db.SaveChanges();
                }

                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public bool ValidaZona(string z)
        {
            foreach (Zonas oZona in db.Zonas.ToList())
            {
                if (oZona.Zona.ToUpper() == z.ToUpper())
                {
                    return true;
                }
            }
            return false;
        }
    }
}

ServiEnCasa_v01/Views/Zonas/Create.cshtml
@model ServiEnCasa_v01.Models.ZonasViewModel
@{
    ViewBag.Title = "Agregar Zona";
    Layout = "~/Views/Shared/_LayoutDash.cshtml";
}

<h2>Agregar Zona</h2>
@Html.AntiForgeryToken()
@using (Html.BeginForm("Create", "Zonas", FormMethod.Post))
{
    <div class="row">
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(z => z.zona, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(z => z.zona, new { @class = "form-control" })
                    @Html.ValidationMessageFor(z => z.zona, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <br />
                    <input type="submit" value="Aceptar" class="btn btn-success" />
                    @Html.ActionLink("Cancelar", "Index", "Zonas", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    </div>
}

ServiEnCasa_v01/Views/Zonas/Delete.cshtml
@model ServiEnCasa_v01.Models.Zonas
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutDash.cshtml";
}
<h2>Eliminar Zona</h2>
<hr />
<h3>¿Esta seguro de eliminar la Zona?</h3>
<br />
<h3>@Html.DisplayFor(model => model.Zona)</h3>
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        @Html.ActionLink("Cancelar", "Index", "Zonas", null, new { @class = "btn btn-default" })
    </div>
}

ServiEnCasa_v01/Views/Zonas/Edit.cshtml
@model ServiEnCasa_v01.Models.ZonasViewModel
@{
    ViewBag.Title = "Editar Zona";
    Layout = "~/Views/Shared/_LayoutDash.cshtml";
}

<h2>Editar Zona</h2>
@Html.AntiForgeryToken()
@using (Html.BeginForm("Edit", "Zonas", FormMethod.Post))
{
    <div class="row">
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(z => z.zona, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(z => z.zona, new { @class = "form-control" })
                    @Html.ValidationMessageFor(z => z.zona, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <br />
                    <input type="submit" value="Aceptar" class="btn btn-success" />
                    @Html.ActionLink("Cancelar", "Index", "Zonas", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    </div>
}

ServiEnCasa_v01/Views/Zonas/Index.cshtml
@model IEnumerable<ServiEnCasa_v01.Models.Zonas>
@{
    <script src="//oss.maxcdn.com/bootbox/4.2.0/bootbox.min.js"></script>
    ViewBag.Title = "Zonas";
    Layout = "~/Views/Shared/_LayoutDash.cshtml";
}

<h2>Administración de Zonas</h2>
<hr />
<div class="container">
    <div class="row col-md-6 col-md-offset-2 custyle">
        <table class="table table-striped custab">
            <thead>
                <a href="@Url.Action("Create","Zonas")" class="btn btn-primary btn-xs pull-right"><b>+</b> Agregar Nueva Zona </a>

                <tr>
                    <th>ID</th>
                    <th>Zona</th>
                    <th class="text-center">Acción</th>
                </tr>
            </thead>
            @foreach (var z in Model)
            {
                <tr>
                    <td>@z.Id_Zona</td>
                    <td>@z.Zona</td>
                    <td class="text-center">
                        <a class='btn btn-info btn-xs' href="@Url.Action("Edit","Zonas",new { id = z.Id_Zona})"><span class="glyphicon glyphicon-edit"></span> Editar</a>
                        <a href="@Url.Action("Delete","Zonas",new { id = z.Id_Zona})" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Eliminar</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>