ServiEnCasa_v01/Models/Presupuestos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiEnCasa_v01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presupuestos()
        {
            this.Servis = new HashSet<Servis>();
        }
    
        public int Id_Presupuesto { get; set; }
        public string Estado { get; set; }
        public System.DateTime Fecha_Vencimiento { get; set; }
        public decimal Precio { get; set; }
        public string Observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servis> Servis { get; set; }
        public virtual Solicitudes Solicitudes { get; set; }
    }
}

ServiEnCasa_v01/Controllers/PresupuestosController.cs
using ServiEnCasa_v01.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiEnCasa_v01.Controllers
{
    public class PresupuestosController : Controller
    {
        private ModeloContainer db = new ModeloContainer();

        [HttpGet]
        public ActionResult PresupuestosSolicitud(int id)
        {
            return View(db.Presupuestos.Where(x=>x.Solicitudes.Id_Solicitud==id).ToList());
        }

        // GET: Presupuestos
        public ActionResult Index()
        {
            return View();
        }

        // GET: Presupuestos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Presupuestos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Presupuestos/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Presupuestos/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Presupuestos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Presupuestos/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Presupuestos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ServiEnCasa_v01/Views/Presupuestos/PresupuestosSolicitud.cshtml
@using ServiEnCasa_v01.Models
@model IEnumerable<ServiEnCasa_v01.Models.Presupuestos>
@{
    ViewBag.Title = "Presupuestos de mi Solicitud";
    Layout = "~/Views/Shared/_LayoutDash.cshtml";
}

<h2>Presupuestos de Mi Solicitud</h2>

<div class="container">
<div class="row">
    <div class="col-md-12">
        @if (Model.Count() > 0)
        {
            foreach (var presupuestos in Model)
            {
                var servi = new Servis();
                servi = presupuestos.Servis.FirstOrDefault();
                <div class="col-md-8">
                    <div class="panel panel-danger">
                        <div class="panel-body">
                            <div class="col-md-3">
                                <img src="@Url.Content(servi.Foto.ToString()    )" class="img-circle img-responsive" />
                            </div>
                            <div class="col-md-5">
                                <div class="header">
                                    <h4 style="color: #3333FF">@servi.Nombre @servi.Apellido </h4>
                                    <h5>@presupuestos.Observacion</h5>
                                </div>
                            </div>
                            <div class="col-md-4">
                                @presupuestos.Fecha_Vencimiento <br />
                                <h2 style="color:red">$ @presupuestos.Precio </h2>

                                <div>
                                    @*<a href="@Url.Action("PresupuestosSolicitudes", "Presupuestos", new { id = @presupuestos.Id_Presupuesto })" class="btn btn-danger"><i class="fa fa-heart-o"></i> Contratar</a>*@
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modalContratar">
                                        Contratar
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="text-muted">&nbsp;<h1>LO SENTIMOS!  :(</h1><br/><h2>Ningun Servi realizo un Presupuesto a tu Solucitud.</h2></div>
}
    </div>
</div>
    </div>

<!-- Modal -->
<div class="modal fade" id="modalContratar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmación</h4>
            </div>
            <div class="modal-body">
                ¿Está seguro que quiere contratar este Servicio ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <input type="submit" href="@Url.Action("Contratar","Presupuestos",new { @idPresupuesto = 1 })" value="Contratar"  class="btn btn-primary" />
            </div>
        </div>
    </div>
</div>